package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.layout.AnchorPane;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class StudentMainController {
	@FXML
	private Label txtsno_0;
	@FXML
	private Label txtcno_0;
	@FXML
	private Label txtclassnum_0;
	@FXML
	private Label txtname_0;
	@FXML
	private Label txtsex_0;
	@FXML
	private AnchorPane txtresult_1;
	@FXML
	private TextField txtcourse_1;
	@FXML
	private Button btnresults_1;
	@FXML
	private TextField txtclass_num_2;
	@FXML
	private TextField txtcourse_2;
	@FXML
	private Button btnresults_2;
	@FXML
	private Label txtresult_2;
	@FXML
	private TextField txtcourse_3;
	@FXML
	private Button btnresult_3;
	@FXML
	private TableView txtcoursechart_3;
	@FXML
	private TableColumn chart_coursename;
	@FXML
	private TableColumn chart_coursepreposition;
	@FXML
	private TableColumn chart_credit;

	// Event Listener on Button[#btnresults_1].onAction
	@FXML
	public void btnresults_1Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnresults_2].onAction
	@FXML
	public void btnresults_2Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnresult_3].onAction
	@FXML
	public void btnresults_3Action(ActionEvent event) {
		// TODO Autogenerated
	}
}
