package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import util.CapsJdbc;
import util.CapsRes;
import util.CapsTableView;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.chart.BarChart;
import javafx.scene.chart.CategoryAxis;
import javafx.scene.chart.NumberAxis;
import javafx.scene.chart.XYChart;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;
import util.CapsJdbc;
import util.CapsTableView;

import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.ResourceBundle;

import javafx.application.Application;
import javafx.collections.FXCollections;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class StudentMainController implements Initializable {
	@FXML
	private Label txtcno_0;
	@FXML
	private Label txtclassnum_0;
	@FXML
	private Label txtname_0;
	@FXML
	private Label txtsex_0;
	@FXML
	private Button btnupdate;
	@FXML
	private Label txtsno_0;
	@FXML
	private TextField txtcourse_1;
	@FXML
	private Button btnresults_1;
	@FXML
	private Label txtresult_1;
	@FXML
	private TextField txtcourse_3;
	@FXML
	private TextField txtclass_num_2;
	@FXML
	private TextField txtcourse_2;
	@FXML
	private Button btnresults_2;
	@FXML
	private Label txtresult_21;
	@FXML
	private Label txtresult_22;
	@FXML
	private TableView<Map<String,String>> chart_1;
	@FXML
	private BarChart<String, Number> analysis;
	@FXML
	private Button btnresult_3;
	@FXML
	private TableView<Map<String,String>> txtcoursechart_3;

	private CapsRes capsRes;

	public String txtUserId;
	// Event Listener on Button[#btnupdate].onAction
	public void updateAction(ActionEvent event) throws Exception{
		// TODO Autogenerated
//		个人信息
		txtUserId="001";
		String strSQL = "select * from student where Sno='"+txtUserId+"';";
		capsRes = CapsJdbc.execSQL(strSQL,null);
		txtsno_0.setText(capsRes.getRs().get(0).get(0));
		txtcno_0.setText(capsRes.getRs().get(0).get(1));
		txtclassnum_0.setText(capsRes.getRs().get(0).get(2));
		txtname_0.setText(capsRes.getRs().get(0).get(3));
		txtsex_0.setText(capsRes.getRs().get(0).get(4));
//		课程信息
		txtUserId="190101";
		String strSQL2 = "select * from studentreport where Sno=?";
		List<Object> params = new ArrayList<>(2);
		params.add(txtUserId);
		capsRes = CapsJdbc.execSQL(strSQL2,params);
		chart_1.setItems(null);
		chart_1.getColumns().clear();
		ArrayList<String> listR = new ArrayList<String>();
		listR.add("学号");
		listR.add("课程号");
		listR.add("成绩");
		CapsTableView.dealTableView(capsRes,chart_1,listR);
//		数据分析
		CategoryAxis xAxis = new CategoryAxis();  
	      xAxis.setCategories(FXCollections.<String>
	      observableArrayList(Arrays.asList("Speed", "User rating", "Milage", "Safety")));
	    xAxis.setLabel("course");
	    NumberAxis yAxis = new NumberAxis();
	    yAxis.setLabel("score");
	    
	    
	    analysis=new BarChart<>(xAxis, yAxis); 
	    XYChart.Series<String, Number> series1 = new XYChart.Series<>();
	    series1.getData().add(new XYChart.Data<>("Speed", 1.0));
	    series1.getData().add(new XYChart.Data<>("User rating", 3.0));
	    series1.getData().add(new XYChart.Data<>("Milage", 5.0));
	    series1.getData().add(new XYChart.Data<>("Safety", 5.0));
	    analysis.getData().addAll(series1);
	}
	// Event Listener on Button[#btnresults_1].onAction
	@FXML
	public void btnresults_1Action(ActionEvent event) {
		txtUserId="190101";
		String strSQL = "select * from studentreport where Sno=? and course=?";
		List<Object> params = new ArrayList<>(2);
		params.add(txtUserId);
		params.add(txtcourse_1.getText());
		capsRes = CapsJdbc.execSQL(strSQL,params);
		chart_1.setItems(null);
		chart_1.getColumns().clear();
		ArrayList<String> listR = new ArrayList<String>();
		listR.add("学号");
		listR.add("课程号");
		listR.add("成绩");
		CapsTableView.dealTableView(capsRes,chart_1,listR);
	}
	// Event Listener on Button[#btnresults_2].onAction
	@FXML
	public void btnresults_2Action(ActionEvent event) {
		String strSQL = "select starttime,endtime from course_room where classroon_num='"+txtclass_num_2.getText()+"' and course="+txtcourse_2.getText()+";";
		capsRes = CapsJdbc.execSQL(strSQL,null);
		txtresult_21.setText(capsRes.getRs().get(0).get(0));
		txtresult_22.setText(capsRes.getRs().get(0).get(1));
//		System.out.println(capsRes.getRs());
	}
	// Event Listener on Button[#btnresult_3].onAction
	@FXML
	public void btnresults_3Action(ActionEvent event) {
		String strSQL = "select * from course where course_num="+txtcourse_3.getText();
		capsRes = CapsJdbc.execSQL(strSQL,null);
		txtcoursechart_3.setItems(null);
		txtcoursechart_3.getColumns().clear();
		ArrayList<String> listR = new ArrayList<String>();
		listR.add("课程号");
		listR.add("课程名");
		listR.add("先修课程号");
		listR.add("学分");
		CapsTableView.dealTableView(capsRes,txtcoursechart_3,listR);
//		System.out.println(txtUserId);
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO 自动生成的方法存根
		String strSQL = "select * from course ";
		capsRes = CapsJdbc.execSQL(strSQL,null);
		txtcoursechart_3.setItems(null);
		txtcoursechart_3.getColumns().clear();
		ArrayList<String> listR = new ArrayList<String>();
		listR.add("课程号");
		listR.add("课程名");
		listR.add("先修课程号");
		listR.add("学分");
		CapsTableView.dealTableView(capsRes,txtcoursechart_3,listR);
//		System.out.println(txtUserId);
		
	}
	public void initData(String string) {
		this.txtUserId=string;
	}
}
