package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.TextArea;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class TeacherMainController {
	@FXML
	private Label txtteachernum_0;
	@FXML
	private Label txtcno_0;
	@FXML
	private Label txtteachername_0;
	@FXML
	private Button btnstudent_look;
	@FXML
	private TableView txtstudentchart;
	@FXML
	private TableColumn chart_sno_1;
	@FXML
	private TableColumn chart_cno_1;
	@FXML
	private TableColumn chart_classnum_1;
	@FXML
	private TableColumn chart_name_1;
	@FXML
	private TableColumn chart_sex_1;
	@FXML
	private TextField txtsno_add;
	@FXML
	private TextField txtcno_add;
	@FXML
	private TextField txtclassnum_add;
	@FXML
	private TextField txtname_add;
	@FXML
	private TextField txtsex_add;
	@FXML
	private Button btnstudent_add;
	@FXML
	private TextField txtsno_delete;
	@FXML
	private Button btnstudent_delete;
	@FXML
	private TextField txtsno_change;
	@FXML
	private TextField txtcno_change;
	@FXML
	private TextField txtclassnum_change;
	@FXML
	private TextField txtname_change;
	@FXML
	private TextField txtsex_change;
	@FXML
	private Button btnstudent_change;
	@FXML
	private Button btncourse_look;
	@FXML
	private TableView txtcoursechart;
	@FXML
	private TableColumn chart_cno_2;
	@FXML
	private TableColumn chart_coursename_2;
	@FXML
	private TableColumn chart_coursepreposition_2;
	@FXML
	private TextField txtcoursenum_add;
	@FXML
	private TextField txtcoursename_add;
	@FXML
	private TextArea txtcoursepreposition_add;
	@FXML
	private Button btncourse_add;
	@FXML
	private TextField txtcoursenum_delete;
	@FXML
	private Button btncourse_delete;
	@FXML
	private TextField txtcoursenum_change;
	@FXML
	private TextField txtcoursename_change;
	@FXML
	private TextArea txtcoursepreposition_change;
	@FXML
	private Button btncourse_change;

	// Event Listener on Button[#btnstudent_look].onAction
	@FXML
	public void btnstudent_lookAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnstudent_add].onAction
	@FXML
	public void btnstudent_addAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnstudent_delete].onAction
	@FXML
	public void btnstudent_deleteAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnstudent_change].onAction
	@FXML
	public void btnstudent_changeAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btncourse_look].onAction
	@FXML
	public void btncourse_lookAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btncourse_add].onAction
	@FXML
	public void btncourse_addAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btncourse_delete].onAction
	@FXML
	public void btncourse_deleteAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btncourse_change].onAction
	@FXML
	public void btncourse_changeAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
